services:
  nginx-proxy:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/nginx-proxy-manager/data:/data
      - /opt/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
  nexus:
    container_name: 'nexus3'
    image: 'sonatype/nexus3'
    restart: unless-stopped
    ports:
      - '8081:8081'
      - '8082:8082'
      - '8083:8083'
      - '8084:8084'
    volumes:
      - '/opt/nexus-data/:/nexus-data/'
  squid:
    container_name: 'squid'
    image: 'ubuntu/squid'
    restart: unless-stopped
    entrypoint: 
      - ""
    command: bash -c "sed -i 's|http_access deny all|http_access allow all|g' /etc/squid/squid.conf;  entrypoint.sh -f /etc/squid/squid.conf -NYC"
    ports:
      - '2128:3128'
    environment:
      - TZ=UTC

